// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.domain.DbContexts;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("back_end.domain.Entities.AuthActionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_action_tokens");
                });

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.Property<int>("Bill_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Bill_Id"));

                    b.Property<int>("Adult_Count")
                        .HasColumnType("int");

                    b.Property<string>("Bill_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Child_Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Closed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Senior_Count")
                        .HasColumnType("int");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tot_Count")
                        .HasColumnType("int");

                    b.Property<int>("Total_Count")
                        .HasColumnType("int");

                    b.HasKey("Bill_Id");

                    b.HasIndex("Session_Id");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("back_end.domain.Entities.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("adult_limit")
                        .HasColumnType("int");

                    b.Property<int>("child_limit")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_viewed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("senior_limit")
                        .HasColumnType("int");

                    b.Property<int>("total_limit")
                        .HasColumnType("int");

                    b.Property<int>("total_view_seconds")
                        .HasColumnType("int");

                    b.Property<int>("total_views")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.Property<int>("Session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Session_Id"));

                    b.Property<DateTime?>("Ended_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("First_Order_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TableGroup_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Table_Id")
                        .HasColumnType("int");

                    b.HasKey("Session_Id");

                    b.HasIndex("Location_Id");

                    b.HasIndex("Menu_Id");

                    b.HasIndex("TableGroup_Id");

                    b.HasIndex("Table_Id");

                    b.ToTable("dining_sessions", t =>
                        {
                            t.HasCheckConstraint("CK_DiningSession_TableAssignment", "(Table_Id IS NOT NULL AND TableGroup_Id IS NULL) OR (Table_Id IS NULL AND TableGroup_Id IS NOT NULL) OR (Table_Id IS NULL AND TableGroup_Id IS NULL)");
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Locations", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Location_Id"));

                    b.Property<string>("Address_Primary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Secondary")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Location_Id");

                    b.HasIndex("User_id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu", b =>
                {
                    b.Property<int>("Menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Menu_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("End_time")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("Start_time")
                        .HasColumnType("time(6)");

                    b.HasKey("Menu_id");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemAssignment", b =>
                {
                    b.Property<int>("Menu_Id")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int>("Item_Id")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Adult_Limit")
                        .HasColumnType("int");

                    b.Property<int>("Child_limit")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Add_On")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastOrdered")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Senior_limit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tot_Limit")
                        .HasColumnType("int");

                    b.Property<int>("Total_Units_Ordered")
                        .HasColumnType("int");

                    b.HasKey("Menu_Id", "Item_Id");

                    b.HasIndex("Item_Id");

                    b.ToTable("menu_item_assignment");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemTag", b =>
                {
                    b.Property<int>("Menu_item_id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_id")
                        .HasColumnType("int");

                    b.HasKey("Menu_item_id", "Tag_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("menu_item_tag");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemView", b =>
                {
                    b.Property<long>("View_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("View_Id"));

                    b.Property<int>("Item_Id")
                        .HasColumnType("int");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("View_Seconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("Viewed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Was_Available")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("View_Id");

                    b.HasIndex("Item_Id");

                    b.HasIndex("Session_Id", "Item_Id")
                        .HasDatabaseName("IX_menu_item_view_session_item");

                    b.HasIndex("Viewed_At", "Location_Id")
                        .HasDatabaseName("IX_menu_item_view_viewed_at_location");

                    b.ToTable("menu_item_view");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuLocations", b =>
                {
                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.HasKey("Menu_Id", "Location_Id");

                    b.HasIndex("Location_Id");

                    b.ToTable("menu_location");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("item_id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .HasColumnType("longtext");

                    b.HasKey("item_id");

                    b.HasIndex("Category_id");

                    b.ToTable("menu_item");
                });

            modelBuilder.Entity("back_end.domain.Entities.OrderItems", b =>
                {
                    b.Property<int>("Order_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_Item_Id"));

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Item_Id")
                        .HasColumnType("int");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Order_Item_Status")
                        .HasColumnType("int");

                    b.Property<int>("Order_Key")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_At_Time")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_Item_Id");

                    b.HasIndex("Item_Id");

                    b.HasIndex("Menu_Id");

                    b.HasIndex("Order_Key");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("back_end.domain.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("request_id"));

                    b.Property<DateTime?>("Claimed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Claimed_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Request_By")
                        .HasColumnType("int");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Table_Id")
                        .HasColumnType("int");

                    b.HasKey("request_id");

                    b.HasIndex("Claimed_By");

                    b.HasIndex("Request_By");

                    b.HasIndex("Session_Id");

                    b.HasIndex("Table_Id");

                    b.ToTable("service_request");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<int>("Bill_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("session_id")
                        .HasColumnType("int");

                    b.HasKey("Order_Id");

                    b.HasIndex("Bill_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("session_id");

                    b.ToTable("session_order");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionParticipant", b =>
                {
                    b.Property<int>("Participant_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Participant_Id"));

                    b.Property<DateTime>("Joined_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Left_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Participant_Id");

                    b.HasIndex("Session_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("session_participant");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableEntity", b =>
                {
                    b.Property<int>("Table_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Table_Id"));

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.Property<string>("QR_Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TableGroup_Id")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("seat_count")
                        .HasColumnType("int");

                    b.Property<int>("table_number")
                        .HasColumnType("int");

                    b.HasKey("Table_Id");

                    b.HasIndex("Location_Id");

                    b.HasIndex("TableGroup_Id");

                    b.ToTable("table_entity");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableGroup", b =>
                {
                    b.Property<int>("TableGroup_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableGroup_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Group_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.HasKey("TableGroup_Id");

                    b.HasIndex("Location_Id");

                    b.ToTable("table_groups");
                });

            modelBuilder.Entity("back_end.domain.Entities.Tag", b =>
                {
                    b.Property<int>("tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tag_id"));

                    b.Property<string>("tag_color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("tag_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("tag_id");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("back_end.domain.Entities.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GoogleSocial")
                        .HasColumnType("longtext");

                    b.Property<bool>("Is_email_confirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Last_Interaction_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Location_id")
                        .HasColumnType("int");

                    b.Property<string>("Normalized_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password_hash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("User_id");

                    b.HasIndex("Location_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("back_end.domain.Entities.AuthActionToken", b =>
                {
                    b.HasOne("back_end.domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Bills")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningSession");
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "Location")
                        .WithMany("DiningSessions")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("DiningSessions")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.TableGroup", "TableGroup")
                        .WithMany("DiningSessions")
                        .HasForeignKey("TableGroup_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("back_end.domain.Entities.TableEntity", "Table")
                        .WithMany("DiningSessions")
                        .HasForeignKey("Table_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Menu");

                    b.Navigation("Table");

                    b.Navigation("TableGroup");
                });

            modelBuilder.Entity("back_end.domain.Entities.Locations", b =>
                {
                    b.HasOne("back_end.domain.Entities.User", null)
                        .WithMany("Locations")
                        .HasForeignKey("User_id");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemAssignment", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("MenuAssignments")
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("MenuItemAssignments")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemTag", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("Menu_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Tag", "Tag")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemView", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany()
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany()
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningSession");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuLocations", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "Location")
                        .WithMany("MenuLocations")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("MenuLocations")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.HasOne("back_end.domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("back_end.domain.Entities.OrderItems", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.SessionOrder", "SessionOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");

                    b.Navigation("SessionOrder");
                });

            modelBuilder.Entity("back_end.domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("back_end.domain.Entities.User", "ClaimedByUser")
                        .WithMany("ClaimedServices")
                        .HasForeignKey("Claimed_By")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_end.domain.Entities.User", "RequestedByUser")
                        .WithMany("RequestedServices")
                        .HasForeignKey("Request_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.TableEntity", "Table")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("Table_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimedByUser");

                    b.Navigation("DiningSession");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.HasOne("back_end.domain.Entities.Billing", "Bill")
                        .WithMany("Orders")
                        .HasForeignKey("Bill_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_Id");

                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Orders")
                        .HasForeignKey("session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("DiningSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionParticipant", b =>
                {
                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Participants")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.User", "User")
                        .WithMany("SessionParticipants")
                        .HasForeignKey("User_Id");

                    b.Navigation("DiningSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableEntity", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "Location")
                        .WithMany("Tables")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.TableGroup", "TableGroup")
                        .WithMany("Tables")
                        .HasForeignKey("TableGroup_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("TableGroup");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableGroup", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "Location")
                        .WithMany("TableGroups")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("back_end.domain.Entities.User", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "PrimaryLocation")
                        .WithMany()
                        .HasForeignKey("Location_id");

                    b.Navigation("PrimaryLocation");
                });

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("back_end.domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Orders");

                    b.Navigation("Participants");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("back_end.domain.Entities.Locations", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("MenuLocations");

                    b.Navigation("TableGroups");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("MenuItemAssignments");

                    b.Navigation("MenuLocations");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.Navigation("MenuAssignments");

                    b.Navigation("MenuItemTags");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableEntity", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableGroup", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("back_end.domain.Entities.Tag", b =>
                {
                    b.Navigation("MenuItemTags");
                });

            modelBuilder.Entity("back_end.domain.Entities.User", b =>
                {
                    b.Navigation("ClaimedServices");

                    b.Navigation("Locations");

                    b.Navigation("Orders");

                    b.Navigation("RequestedServices");

                    b.Navigation("SessionParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
